In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Challenge_Dataset.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4549 entries, 0 to 4548
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   PROGRAM NAME              2248 non-null   object 
 1   PROGRAM CODE              1914 non-null   object 
 2   PROGRAM CODE 2            318 non-null    object 
 3   PROGRAM CODE 3            17 non-null     object 
 4   COURSE CODE               847 non-null    object 
 5   COURSE CODE 2             803 non-null    object 
 6   COURSE CODE3              331 non-null    object 
 7   COURSE CODE 4             237 non-null    object 
 8   WIL TYPE                  827 non-null    object 
 9   WIL TYPE 2                798 non-null    object 
 10  WIL TYPE 3                331 non-null    object 
 11  WIL TYPE 4                237 non-null    object 
 12  Primary Key               4439 non-null   object 
 13  Contact Name              4549 non-null   object 
 14  Address 

In [4]:
print ("Rows     : " ,df.shape[0])
print ("Columns  : " ,df.shape[1])
print ("\nFeatures : \n" ,df.columns.tolist())
print ("\nUnique values :  \n",df.nunique())

Rows     :  4549
Columns  :  21

Features : 
 ['PROGRAM NAME', 'PROGRAM CODE', 'PROGRAM CODE 2 ', 'PROGRAM CODE 3', 'COURSE CODE', 'COURSE CODE 2', 'COURSE CODE3', 'COURSE CODE 4', 'WIL TYPE', 'WIL TYPE 2', 'WIL TYPE 3', 'WIL TYPE 4', 'Primary Key', 'Contact Name', 'Address', 'City', 'Postal Code', 'Paid/Unpaid', '22F\n# of Students Placed', '23W\n# of Students Placed', 'PAC/PLACE/CAREER']

Unique values :  
 PROGRAM NAME                  109
PROGRAM CODE                   75
PROGRAM CODE 2                 18
PROGRAM CODE 3                  2
COURSE CODE                    14
COURSE CODE 2                 149
COURSE CODE3                    4
COURSE CODE 4                   2
WIL TYPE                        6
WIL TYPE 2                      5
WIL TYPE 3                      3
WIL TYPE 4                      2
Primary Key                  3449
Contact Name                 2436
Address                      1631
City                          288
Postal Code                   356
Paid/Unpa

In [5]:
df['City'].unique()

array([nan, 'Windsor, ON', 'Kingsville, ON', ' Chatham, ON ',
       'LaSalle, ON ', 'Etobicoke, ON ', 'Chatham, ON', 'Ridgetown, ON ',
       'Amherstburg, ON ', 'Leamington, ON ', 'Chatham, ON ',
       'Tecumseh, ON', 'North York, ON', 'Windsor, ON ', 'LaSalle, ON',
       'Wheatley, ON', 'Scarborough, ON ', 'Kitchener, ON',
       'Alliston, ON', 'Wheatley, ON ', 'Belle River, ON',
       'Amherstburg, ON', ' Tecumseh, ON ', 'Toronto, ON',
       'Maidstone, ON ', 'Brampton Ontario', 'Brampton, ON',
       'Tecumseh, ON ', 'Mississauga, ON ', 'Orléans, ON ', 'London, ON',
       'Oldcastle, ON ', 'Kingsville, On', 'Leamington, ON',
       'Woodstock, ON ', 'Collingwood, ON', 'Belle River, ON ',
       'Chatham,ON', 'Essex, ON ', 'Blenheim, ON', 'Tilbury, ON ',
       'Guelph, ON', 'Dundas, ON', 'Strathroy ON', 'Essex, ON',
       'Orillia, ON', 'Wallaceburg, ON', 'Collingwood, ON ', ' Essex, ON',
       ' Tilbury, ON ', 'Fergus, ON ', 'Emeryville, ON', 'Georgetown, ON',
       'Wal

In [6]:
df['City'] = df['City'].str.lower()
# Replace 'ON', 'on', and 'Ontario' with an empty string
df['City'] = df['City'].str.replace(r'(?i)(, on|, ontario|,on|, ab|, bc| ontario| on)', '', regex=True)

# To remove leading and trailing spaces
df['City'] = df['City'].str.strip()

# To remove extra spaces (if any)
df['City'] = df['City'].str.replace('\s+', ' ', regex=True)

# Display unique values after removal
unique_values = df['City'].unique()
print(unique_values)


[nan 'windsor' 'kingsville' 'chatham' 'lasalle' 'etobicoke' 'ridgetown'
 'amherstburg' 'leamington' 'tecumseh' 'north york' 'wheatley'
 'scarborough' 'kitchener' 'alliston' 'belle river' 'toronto' 'maidstone'
 'brampton' 'mississauga' 'orléans' 'london' 'oldcastle' 'woodstock'
 'collingwood' 'essex' 'blenheim' 'tilbury' 'guelph' 'dundas' 'strathroy'
 'orillia' 'wallaceburg' 'fergus' 'emeryville' 'georgetown' 'lucan'
 'thunder bay' 'shelburne' 'corunna' 'hamilton' 'goderich' 'sarnia'
 'st. thomas' 'calgary' 'edmonton' 'ingersoll' 'thamesville' 'victoria'
 'dutton' 'wingham' 'richmond hill' 'new hamburg' 'ottawa' 'lakeshore'
 'west lorne' 'st thomas' 'london westmount gdns ltc' 'petrolia'
 'lasalle.' 'owen sound' 'orangeville' 'toronto/ottawa' 'burlington'
 'newmarket' 'whitby' 'waterloo' 'gta' 'port hope' 'blind river' 'dresden'
 'stoney point' 'dryden' 'listowell' 'hanover' 'courtright'
 'st. catharines' 'st. marys' 'markham' 'greater napanee' 'windsor / gta'
 'thunderbay' 'pembroke' '

In [7]:
df['PAC/PLACE/CAREER'].unique()

array(['PAC', 'Placement ', nan, 'placement ', 'Job Shadow ', 'Placement',
       'Orbis ', 'Career Fair ', 'Career Fair (first responder)',
       'Job Posting ', 'Coordinator Contacts', 'Lido commitment letters ',
       'coordinator contact list ', 'Coordinator contact list'],
      dtype=object)

In [8]:
df['PAC/PLACE/CAREER'] = df['PAC/PLACE/CAREER'].str.lower()
# Replace 'ON', 'on', and 'Ontario' with an empty string
df['PAC/PLACE/CAREER'] = df['PAC/PLACE/CAREER'].str.replace(r'(?i)( list|)', '', regex=True)

# To remove leading and trailing spaces
df['PAC/PLACE/CAREER'] = df['PAC/PLACE/CAREER'].str.strip()

# To remove extra spaces (if any)
df['PAC/PLACE/CAREER'] = df['PAC/PLACE/CAREER'].str.replace('\s+', ' ', regex=True)

df['PAC/PLACE/CAREER'] = df['PAC/PLACE/CAREER'].replace({
    'career fair (first responder)': 'career fair',
    'coordinator contacts': 'coordinator contact'
})


# Display unique values after removal
unique_values = df['PAC/PLACE/CAREER'].unique()
print(unique_values)

['pac' 'placement' nan 'job shadow' 'orbis' 'career fair' 'job posting'
 'coordinator contact' 'lido commitment letters']


In [9]:
df.keys()

Index(['PROGRAM NAME', 'PROGRAM CODE', 'PROGRAM CODE 2 ', 'PROGRAM CODE 3',
       'COURSE CODE', 'COURSE CODE 2', 'COURSE CODE3', 'COURSE CODE 4',
       'WIL TYPE', 'WIL TYPE 2', 'WIL TYPE 3', 'WIL TYPE 4', 'Primary Key',
       'Contact Name', 'Address', 'City', 'Postal Code', 'Paid/Unpaid',
       '22F\n# of Students Placed', '23W\n# of Students Placed',
       'PAC/PLACE/CAREER'],
      dtype='object')

In [10]:
df[df["PROGRAM NAME"].isnull() & df[["PROGRAM CODE", "PROGRAM CODE 2 ", "PROGRAM CODE 3"]].notnull().any(axis=1)]

Empty DataFrame
Columns: [PROGRAM NAME, PROGRAM CODE, PROGRAM CODE 2 , PROGRAM CODE 3, COURSE CODE, COURSE CODE 2, COURSE CODE3, COURSE CODE 4, WIL TYPE, WIL TYPE 2, WIL TYPE 3, WIL TYPE 4, Primary Key, Contact Name, Address, City, Postal Code, Paid/Unpaid, 22F
# of Students Placed, 23W
# of Students Placed, PAC/PLACE/CAREER]
Index: []

[0 rows x 21 columns]

In [11]:
df[df["COURSE CODE"].isnull() & df[["COURSE CODE 2", "COURSE CODE3", "COURSE CODE 4"]].notnull().any(axis=1)]

Empty DataFrame
Columns: [PROGRAM NAME, PROGRAM CODE, PROGRAM CODE 2 , PROGRAM CODE 3, COURSE CODE, COURSE CODE 2, COURSE CODE3, COURSE CODE 4, WIL TYPE, WIL TYPE 2, WIL TYPE 3, WIL TYPE 4, Primary Key, Contact Name, Address, City, Postal Code, Paid/Unpaid, 22F
# of Students Placed, 23W
# of Students Placed, PAC/PLACE/CAREER]
Index: []

[0 rows x 21 columns]

In [12]:
df[df["WIL TYPE"].isnull() & df[["WIL TYPE 2", "WIL TYPE 3", "WIL TYPE 4"]].notnull().any(axis=1)]

Empty DataFrame
Columns: [PROGRAM NAME, PROGRAM CODE, PROGRAM CODE 2 , PROGRAM CODE 3, COURSE CODE, COURSE CODE 2, COURSE CODE3, COURSE CODE 4, WIL TYPE, WIL TYPE 2, WIL TYPE 3, WIL TYPE 4, Primary Key, Contact Name, Address, City, Postal Code, Paid/Unpaid, 22F
# of Students Placed, 23W
# of Students Placed, PAC/PLACE/CAREER]
Index: []

[0 rows x 21 columns]

In [13]:
df[df["City"].isnull() & df[["Postal Code"]].notnull().any(axis=1)]

PROGRAM NAME PROGRAM CODE PROGRAM CODE 2   \
828                       Collborative Nursing         H850            K950   
969  Business Administration - Human Resources         B880             NaN   

    PROGRAM CODE 3 COURSE CODE COURSE CODE 2 COURSE CODE3 COURSE CODE 4  \
828            NaN         NaN           NaN          NaN           NaN   
969            NaN         NaN           NaN          NaN           NaN   

    WIL TYPE WIL TYPE 2  ... WIL TYPE 4                           Primary Key  \
828      NaN        NaN  ...        NaN  ef5cd56c-b783-41f4-b39d-da9c4e2afa38   
969      NaN        NaN  ...        NaN  74333218-c876-4870-bd0d-d7f12c50e178   

    Contact Name                             Address City Postal Code  \
828      Felicia  Ouellette Ave, Windsor, ON N9A 4J8  NaN  ON N9A 4J8   
969     Michelle                     Sandwich St S.   NaN     N9V 2A5   

    Paid/Unpaid  22F\n# of Students Placed  23W\n# of Students Placed  \
828         NaN                        3.0                        NaN   
969         NaN                        3.0                        NaN   

     PAC/PLACE/CAREER  
828         placement  
969         placement  

[2 rows x 21 columns]

In [14]:
dt = df[["PROGRAM NAME", "COURSE CODE", "WIL TYPE", "Contact Name", 'Address', 'City', '22F\n# of Students Placed', 'PAC/PLACE/CAREER']]

In [15]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4549 entries, 0 to 4548
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   PROGRAM NAME              2248 non-null   object 
 1   COURSE CODE               847 non-null    object 
 2   WIL TYPE                  827 non-null    object 
 3   Contact Name              4549 non-null   object 
 4   Address                   2058 non-null   object 
 5   City                      1905 non-null   object 
 6   22F
# of Students Placed  726 non-null    float64
 7   PAC/PLACE/CAREER          4394 non-null   object 
dtypes: float64(1), object(7)
memory usage: 284.4+ KB


In [16]:
db = dt[dt["City"].isnull() & df[["Address"]].notnull().any(axis=1)]

In [17]:
filtered_df = dt[dt["City"].isnull() & dt[["Address"]].notnull().any(axis=1)]

# Save the filtered DataFrame to a CSV file
filtered_df.to_csv('address.csv', index=False)

In [18]:
db['City'] = db['Address'].str.split(',').str[1].str.strip()

C:\Users\solan\AppData\Local\Temp\ipykernel_23312\1651746350.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db['City'] = db['Address'].str.split(',').str[1].str.strip()


In [19]:
db['City']

828                Windsor
969                    NaN
982                    NaN
1023                   NaN
1032                   NaN
               ...        
3794       CHATHAM ONTARIO
3795       WINDSOR ONTARIO
3796              McGregor
3797    Windsor ON N9C 2G4
3798    Windsor ON N8N 5G2
Name: City, Length: 312, dtype: object

In [20]:
#db.to_csv('add.csv', index=False)

In [21]:
rows_to_delete = dt[dt["City"].isnull() & dt[["Address"]].notnull().any(axis=1)].index

# Drop the rows based on the index
dt.drop(rows_to_delete, inplace=True)

C:\Users\solan\AppData\Local\Temp\ipykernel_23312\655770842.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt.drop(rows_to_delete, inplace=True)


In [22]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4237 entries, 0 to 4548
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   PROGRAM NAME              1937 non-null   object 
 1   COURSE CODE               542 non-null    object 
 2   WIL TYPE                  523 non-null    object 
 3   Contact Name              4237 non-null   object 
 4   Address                   1746 non-null   object 
 5   City                      1905 non-null   object 
 6   22F
# of Students Placed  601 non-null    float64
 7   PAC/PLACE/CAREER          4142 non-null   object 
dtypes: float64(1), object(7)
memory usage: 297.9+ KB


In [23]:
new_data = pd.read_csv('final_add.csv')

# Concatenate 'new_data' with 'dt'
dt = pd.concat([dt, new_data], ignore_index=True)

In [24]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4549 entries, 0 to 4548
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   PROGRAM NAME              2248 non-null   object 
 1   COURSE CODE               847 non-null    object 
 2   WIL TYPE                  827 non-null    object 
 3   Contact Name              4549 non-null   object 
 4   Address                   2058 non-null   object 
 5   City                      2217 non-null   object 
 6   22F
# of Students Placed  726 non-null    float64
 7   PAC/PLACE/CAREER          4394 non-null   object 
dtypes: float64(1), object(7)
memory usage: 284.4+ KB


In [25]:
dt = dt.drop("Address", axis=1)

In [26]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4549 entries, 0 to 4548
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   PROGRAM NAME              2248 non-null   object 
 1   COURSE CODE               847 non-null    object 
 2   WIL TYPE                  827 non-null    object 
 3   Contact Name              4549 non-null   object 
 4   City                      2217 non-null   object 
 5   22F
# of Students Placed  726 non-null    float64
 6   PAC/PLACE/CAREER          4394 non-null   object 
dtypes: float64(1), object(6)
memory usage: 248.9+ KB


In [27]:
dt['City'] = dt['City'].str.lower()
dt['City'].unique()

array([nan, 'windsor', 'kingsville', 'chatham', 'lasalle', 'etobicoke',
       'ridgetown', 'amherstburg', 'leamington', 'tecumseh', 'north york',
       'wheatley', 'scarborough', 'kitchener', 'alliston', 'belle river',
       'toronto', 'maidstone', 'brampton', 'mississauga', 'orléans',
       'london', 'oldcastle', 'woodstock', 'collingwood', 'essex',
       'blenheim', 'tilbury', 'guelph', 'dundas', 'strathroy', 'orillia',
       'wallaceburg', 'fergus', 'emeryville', 'georgetown', 'lucan',
       'thunder bay', 'shelburne', 'corunna', 'hamilton', 'goderich',
       'sarnia', 'st. thomas', 'calgary', 'edmonton', 'ingersoll',
       'thamesville', 'victoria', 'dutton', 'wingham', 'richmond hill',
       'new hamburg', 'ottawa', 'lakeshore', 'west lorne', 'st thomas',
       'london westmount gdns ltc', 'petrolia', 'lasalle.', 'owen sound',
       'orangeville', 'toronto/ottawa', 'burlington', 'newmarket',
       'whitby', 'waterloo', 'gta', 'port hope', 'blind river', 'dresden',
   

In [28]:
replace_cols = ['City']
for i in replace_cols : 
    dt[i]  = dt[i].replace({'winsdor' : 'windsor', 'kingsvillle' : 'kingsville', 'old castle' : 'oldcastle', 'oldcaste' : 'oldcastle', 'mcdougall st suite' : 'windsor', 'st thomas' : 'st. thomas', 'london westmount gdns ltc' : 'london', 'tecumseh,' : 'tecumseh', 'windsor,' : 'windsor', 'chatham-kent' : 'chatham'})

In [29]:
dt['City'].unique()

array([nan, 'windsor', 'kingsville', 'chatham', 'lasalle', 'etobicoke',
       'ridgetown', 'amherstburg', 'leamington', 'tecumseh', 'north york',
       'wheatley', 'scarborough', 'kitchener', 'alliston', 'belle river',
       'toronto', 'maidstone', 'brampton', 'mississauga', 'orléans',
       'london', 'oldcastle', 'woodstock', 'collingwood', 'essex',
       'blenheim', 'tilbury', 'guelph', 'dundas', 'strathroy', 'orillia',
       'wallaceburg', 'fergus', 'emeryville', 'georgetown', 'lucan',
       'thunder bay', 'shelburne', 'corunna', 'hamilton', 'goderich',
       'sarnia', 'st. thomas', 'calgary', 'edmonton', 'ingersoll',
       'thamesville', 'victoria', 'dutton', 'wingham', 'richmond hill',
       'new hamburg', 'ottawa', 'lakeshore', 'west lorne', 'petrolia',
       'lasalle.', 'owen sound', 'orangeville', 'toronto/ottawa',
       'burlington', 'newmarket', 'whitby', 'waterloo', 'gta',
       'port hope', 'blind river', 'dresden', 'stoney point', 'dryden',
       'listowell',

In [30]:
dt.keys()

Index(['PROGRAM NAME', 'COURSE CODE', 'WIL TYPE', 'Contact Name', 'City',
       '22F\n# of Students Placed', 'PAC/PLACE/CAREER'],
      dtype='object')

In [31]:
dt.rename(columns={'22F\n# of Students Placed': 'StudentsPlacedFall22', 'PROGRAM NAME': 'ProgramName', 'COURSE CODE' : 'CourseCode', 'WIL TYPE' : 'WilType', 'Contact Name' : 'ContactName'}, inplace=True)

In [32]:
dt.keys()

Index(['ProgramName', 'CourseCode', 'WilType', 'ContactName', 'City',
       'StudentsPlacedFall22', 'PAC/PLACE/CAREER'],
      dtype='object')

In [33]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4549 entries, 0 to 4548
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   ProgramName           2248 non-null   object 
 1   CourseCode            847 non-null    object 
 2   WilType               827 non-null    object 
 3   ContactName           4549 non-null   object 
 4   City                  2217 non-null   object 
 5   StudentsPlacedFall22  726 non-null    float64
 6   PAC/PLACE/CAREER      4394 non-null   object 
dtypes: float64(1), object(6)
memory usage: 248.9+ KB


In [34]:
dt['City'] = dt['City'].apply(lambda x: 'windsor' if isinstance(x, str) and 'windsor' in x.lower() else x)
dt['City'].unique()

array([nan, 'windsor', 'kingsville', 'chatham', 'lasalle', 'etobicoke',
       'ridgetown', 'amherstburg', 'leamington', 'tecumseh', 'north york',
       'wheatley', 'scarborough', 'kitchener', 'alliston', 'belle river',
       'toronto', 'maidstone', 'brampton', 'mississauga', 'orléans',
       'london', 'oldcastle', 'woodstock', 'collingwood', 'essex',
       'blenheim', 'tilbury', 'guelph', 'dundas', 'strathroy', 'orillia',
       'wallaceburg', 'fergus', 'emeryville', 'georgetown', 'lucan',
       'thunder bay', 'shelburne', 'corunna', 'hamilton', 'goderich',
       'sarnia', 'st. thomas', 'calgary', 'edmonton', 'ingersoll',
       'thamesville', 'victoria', 'dutton', 'wingham', 'richmond hill',
       'new hamburg', 'ottawa', 'lakeshore', 'west lorne', 'petrolia',
       'lasalle.', 'owen sound', 'orangeville', 'toronto/ottawa',
       'burlington', 'newmarket', 'whitby', 'waterloo', 'gta',
       'port hope', 'blind river', 'dresden', 'stoney point', 'dryden',
       'listowell',

In [35]:
replace_cols = ['City']
for i in replace_cols : 
    dt[i]  = dt[i].replace({'chatham kent' : 'chatham-kent', 'niagara-on-the-lake' : 'niagara', 'rr1 ilderton' : 'ilderton', 'toronto/ottawa' : 'toronto', 'amhersburg' : 'amherstburg', 'harrow' : 'essex', 'horrow' : 'essex', 'huintsville' : 'huntsville', 'north vancouver' : 'vancouver', 'wallacburg' : 'wallaceburg', 'whetaley' : 'wheatley', 'chatham' : 'chatham-kent', 'lasalle.' : 'lasalle'})

In [36]:
dt['City'].unique()

array([nan, 'windsor', 'kingsville', 'chatham-kent', 'lasalle',
       'etobicoke', 'ridgetown', 'amherstburg', 'leamington', 'tecumseh',
       'north york', 'wheatley', 'scarborough', 'kitchener', 'alliston',
       'belle river', 'toronto', 'maidstone', 'brampton', 'mississauga',
       'orléans', 'london', 'oldcastle', 'woodstock', 'collingwood',
       'essex', 'blenheim', 'tilbury', 'guelph', 'dundas', 'strathroy',
       'orillia', 'wallaceburg', 'fergus', 'emeryville', 'georgetown',
       'lucan', 'thunder bay', 'shelburne', 'corunna', 'hamilton',
       'goderich', 'sarnia', 'st. thomas', 'calgary', 'edmonton',
       'ingersoll', 'thamesville', 'victoria', 'dutton', 'wingham',
       'richmond hill', 'new hamburg', 'ottawa', 'lakeshore',
       'west lorne', 'petrolia', 'owen sound', 'orangeville',
       'burlington', 'newmarket', 'whitby', 'waterloo', 'gta',
       'port hope', 'blind river', 'dresden', 'stoney point', 'dryden',
       'listowell', 'hanover', 'courtright',

In [47]:
dt.keys()

Index(['ProgramName', 'CourseCode', 'WilType', 'ContactName', 'City',
       'StudentsPlacedFall22', 'PAC/PLACE/CAREER'],
      dtype='object')

In [55]:
dt[dt["ProgramName"].isnull() & dt[["CourseCode"]].notnull().any(axis=1)]

Empty DataFrame
Columns: [ProgramName, CourseCode, WilType, ContactName, City, StudentsPlacedFall22, PAC/PLACE/CAREER]
Index: []

In [57]:
#dt = dt.drop("CourseCode", axis=1)
dt['CourseCode'].unique()
dt['ProgramName'].unique()

array(['Business',
       'Electromechanical Engineering Technology/Technician - Robotics ',
       'B875 - ADVERTISING AND MARKETING COMMUNICATION MANAGEMENT/ B792 - WEB AND INTERACTIVE ADVERTISING',
       'International Business Management - Logistics Systems',
       'Mobile Applications Development', 'Event Management ',
       'Community & Justice Services', 'Power Engineering ',
       'Honours Bachelor of Applied Arts in Social Justice & Legal Studies',
       'Academic and Career Entrance / College and Employment Preperation',
       'Powerline Technician ', 'Respiratory Therapy',
       'Plumbing Techniques/Plumbing Apprenticeship',
       'Electrical Engineering Technician', 'Architectural Technnology ',
       'Landscape Horticulture', 'Graphic Design',
       'Mechanical Engineering Technology - Automotive Product Design',
       'Occupational Therapist Assistant / Physiotherapist Assistant',
       'Brick and Stone Mason',
       'Electronics Engineering Technology - Indu

In [48]:
placed = dt[dt['StudentsPlacedFall22'].notna()]
not_placed = dt[dt['StudentsPlacedFall22'].isna()]

In [49]:
not_placed.info()
placed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3823 entries, 0 to 4548
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   ProgramName           1549 non-null   object 
 1   CourseCode            460 non-null    object 
 2   WilType               451 non-null    object 
 3   ContactName           3823 non-null   object 
 4   City                  1791 non-null   object 
 5   StudentsPlacedFall22  0 non-null      float64
 6   PAC/PLACE/CAREER      3669 non-null   object 
dtypes: float64(1), object(6)
memory usage: 238.9+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 726 entries, 579 to 4482
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   ProgramName           699 non-null    object 
 1   CourseCode            387 non-null    object 
 2   WilType               376 non-null    object 
 3   ContactName   

In [50]:
placed['City'].unique()

array([nan, 'windsor', 'kingsville', 'chatham-kent', 'lasalle',
       'etobicoke', 'ridgetown', 'amherstburg', 'leamington', 'tecumseh',
       'north york', 'wheatley', 'scarborough', 'kitchener', 'alliston',
       'belle river', 'toronto', 'maidstone', 'brampton', 'mississauga',
       'orléans', 'woodstock', 'collingwood', 'oldcastle', 'blenheim',
       'strathroy', 'essex', 'orillia', 'wallaceburg', 'tilbury',
       'fergus', 'emeryville', 'hamilton', 'goderich', 'sarnia',
       'st. thomas', 'edmonton', 'ingersoll', 'richmond hill',
       'owen sound', 'orangeville', 'burlington', 'london', 'newmarket',
       'ottawa', 'other', 'stratford', 'belleville', 'tillsonburg',
       'point edward', 'glencoe', 'grand bend', 'grand valley', 'komoka',
       'mount brydges', 'newbury', 'thamesville', 'vancouver'],
      dtype=object)

In [51]:
not_placed['City'].unique()

array([nan, 'windsor', 'london', 'mississauga', 'oldcastle', 'kingsville',
       'leamington', 'chatham-kent', 'essex', 'lasalle', 'blenheim',
       'tilbury', 'tecumseh', 'ridgetown', 'guelph', 'dundas',
       'georgetown', 'wallaceburg', 'scarborough', 'lucan', 'toronto',
       'maidstone', 'thunder bay', 'shelburne', 'corunna', 'belle river',
       'north york', 'sarnia', 'calgary', 'amherstburg', 'alliston',
       'thamesville', 'wheatley', 'victoria', 'dutton', 'wingham',
       'kitchener', 'new hamburg', 'brampton', 'ottawa', 'lakeshore',
       'west lorne', 'fergus', 'st. thomas', 'petrolia', 'woodstock',
       'whitby', 'waterloo', 'strathroy', 'gta', 'port hope',
       'blind river', 'dresden', 'stoney point', 'dryden', 'listowell',
       'hanover', 'courtright', 'st. catharines', 'st. marys', 'markham',
       'greater napanee', 'thunderbay', 'pembroke', 'mooretown',
       'ruthven', 'winchester', 'bolton', 'banff', 'sudbury', 'bath',
       'kincardine', 'mitchel

In [52]:
placed.to_csv('placed.csv', index=False)


In [45]:
placed['City'].unique()

In [53]:
placed.keys()

Index(['ProgramName', 'CourseCode', 'WilType', 'ContactName', 'City',
       'StudentsPlacedFall22', 'PAC/PLACE/CAREER'],
      dtype='object')

In [61]:
not_placed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3823 entries, 0 to 4548
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   ProgramName           1549 non-null   object 
 1   CourseCode            460 non-null    object 
 2   WilType               451 non-null    object 
 3   ContactName           3823 non-null   object 
 4   City                  1791 non-null   object 
 5   StudentsPlacedFall22  3823 non-null   float64
 6   PAC/PLACE/CAREER      3669 non-null   object 
dtypes: float64(1), object(6)
memory usage: 238.9+ KB


In [60]:
not_placed['StudentsPlacedFall22'] = not_placed['StudentsPlacedFall22'].fillna(0)

C:\Users\solan\AppData\Local\Temp\ipykernel_23312\1473898298.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_placed['StudentsPlacedFall22'] = not_placed['StudentsPlacedFall22'].fillna(0)


In [62]:
not_placed.to_csv('not_placed.csv', index=False)